# Intro

This notebook gives an intro to our project and its components. It also showcases what can be done

## Load & Inspect OCELs

First, we can load ocels and inspect them

In [6]:
import pm4py

ocel = pm4py.read_ocel2_json("../data/ocel2-p2p.json")

In [7]:
ocel.events

,ocel:eid,ocel:timestamp,ocel:activity,lifecycle,resource
9786,event:1,2022-04-01 09:26:00+00:00,Create Purchase Requisition,complete,Manufacturing Department
1598,event:3,2022-04-02 14:16:00+00:00,Approve Purchase Requisition,complete,Procurement Requisition Manager
9787,event:9,2022-04-04 08:37:00+00:00,Create Purchase Requisition,complete,Manufacturing Department
9788,event:11,2022-04-04 09:25:00+00:00,Create Purchase Requisition,complete,Manufacturing Department
11442,event:13,2022-04-04 09:44:00+00:00,Delegate Purchase Requisition Approval,complete,Manufacturing Department
...,...,...,...,...,...
8187,event:29334,2024-10-29 07:55:00+00:00,Create Invoice Receipt,complete,Finance/Account Department
14670,event:29336,2024-10-29 08:10:00+00:00,Perform Two-Way Match,complete,Finance/Account Department
12727,event:29338,2024-10-29 14:14:00+00:00,Execute Payment,complete,Finance/Account Department
12728,event:29339,2024-10-29 22:22:00+00:00,Execute Payment,complete,Finance/Account Department
12729,event:29341,2024-10-31 20:28:00+00:00,Execute Payment,complete,Finance/Account Department

In [10]:
ocel_new = pm4py.read_ocel2_sqlite("../data/new.sqlite")

In [21]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../data/new.sqlite")
objects = pd.read_sql("SELECT * FROM object", conn)
events = pd.read_sql("SELECT * FROM event", conn)
conn.close()
print(objects)
events

  ocel_id ocel_type
0   user1      user
1   user2      user
2  order1     order
3   user1      user

  ocel_id      ocel_type
0  event1   Create Order
1  event2  Receive Order